# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

permuC <- function(x) {
    .Call(`_LA_permuC`, x)
}

seqC <- function(a, b) {
    .Call(`_LA_seqC`, a, b)
}

rLHDC <- function(n, k) {
    .Call(`_LA_rLHDC`, n, k)
}

dijC <- function(X, i, j, q = 1L) {
    .Call(`_LA_dijC`, X, i, j, q)
}

phi_pC <- function(X, p = 15L, q = 1L) {
    .Call(`_LA_phi_pC`, X, p, q)
}

MaxProCriterionC <- function(X) {
    .Call(`_LA_MaxProCriterionC`, X)
}

corC <- function(x, y) {
    .Call(`_LA_corC`, x, y)
}

MaxAbsCorC <- function(X) {
    .Call(`_LA_MaxAbsCorC`, X)
}

AvgAbsCorC <- function(X) {
    .Call(`_LA_AvgAbsCorC`, X)
}

exchangeC <- function(X, j, type = "col") {
    .Call(`_LA_exchangeC`, X, j, type)
}

LA_LHDC <- function(n, k, m = 100L, N = 5000L, OC = "phi_p", p = 15L, q = 1L) {
    .Call(`_LA_LA_LHDC`, n, k, m, N, OC, p, q)
}

factorialC <- function(x) {
    .Call(`_LA_factorialC`, x)
}

modC <- function(a, b) {
    .Call(`_LA_modC`, a, b)
}

rOofAC <- function(n, k) {
    .Call(`_LA_rOofAC`, n, k)
}

PWOC <- function(X) {
    .Call(`_LA_PWOC`, X)
}

TC <- function(X) {
    .Call(`_LA_TC`, X)
}

MOMC <- function(X) {
    .Call(`_LA_MOMC`, X)
}

LA_OofAC <- function(n, k, m = 100L, N = 5000L) {
    .Call(`_LA_LA_OofAC`, n, k, m, N)
}

D <- function(X) {
    .Call(`_LA_D`, X)
}

A <- function(X) {
    .Call(`_LA_A`, X)
}

GscoreC <- function(X, x) {
    .Call(`_LA_GscoreC`, X, x)
}

rSign <- function(m = 2L) {
    .Call(`_LA_rSign`, m)
}

G <- function(Y) {
    .Call(`_LA_G`, Y)
}

LA_OptC <- function(n, lb, ub, m = 100L, N = 5000L, OC = "D", alpha = 0.1) {
    .Call(`_LA_LA_OptC`, n, lb, ub, m, N, OC, alpha)
}

